<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
    <meta property="og:locale" content="pt_BR">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="REPLACE_PAGE_AUTHOR" />
    <meta name="description" content="REPLACE_PAGE_DESCRIPTION" />
    <meta name="url" content="REPLACE_URL" />
    <meta name="robots" content="REPLACE_ROBOTS" />
    <meta name="googlebot" content="REPLACE_ROBOTS" />
    <meta property="og:title" content="REPLACE_PAGE_TITLE" />
    <meta property="og:site_name" content="REPLACE_PAGE_TITLE">
    <meta property="og:description" content="REPLACE_PAGE_DESCRIPTION" />
    <meta property="og:image" content="REPLACE_OGG">
    <meta property="og:image:type" content="image/jpeg">
    <meta property="og:image:width" content="800">
    <meta property="og:image:height" content="600">
    <meta property="og:type" content="website">
    <meta property="og:url" content="REPLACE_URL" />
    <meta name="keywords" content="REPLACE_KEYWORDS" />
    <link rel="shortcut icon" sizes="144x144" href="REPLACE_ICON">
    <title><?= $PAGE_TITLE ?></title>
    <link rel="canonical" href="REPLACE_CANONICAL" />
    <link rel="icon" sizes="144x144" href="REPLACE_ICON">
</head>
<body>
    
</body>
</html>